name: Release Android App

on:
  push:
    tags:
      - 'v*' # A single, broad trigger for ALL version tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Sync Android version (package.json → build.gradle)
        run: npm run sync-ver

      - name: Create google-services.json file
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_RAW }}" > android/app/google-services.json

      - name: Verify google-services.json Checksum
        run: md5sum android/app/google-services.json

      - name: Decode Keystore
        run: base64 --decode <<< "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" > android/app/release.keystore
        
      - name: Create gradle.properties for signing
        run: |
          echo "storeFile=release.keystore" >> android/gradle.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/gradle.properties

      - name: Build web app (Next.js)
        run: npm run build

      - name: Sync Capacitor project
        run: npx cap sync android

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # A trusted, open-source distribution of OpenJDK

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Android release with Gradle
        run: ./gradlew assembleRelease
        working-directory: android
        env:
          ORG_GRADLE_PROJECT_androidKeystorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ORG_GRADLE_PROJECT_androidKeyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Rename APK
        id: find_and_rename_apk
        run: |
          # Find the original APK path
          ORIGINAL_PATH=$(find android/app/build/outputs/apk/release/ -name "*.apk" | head -n 1)
          echo "Original APK found at: $ORIGINAL_PATH"
          
          # Define the new name using the Git tag
          NEW_NAME="tgatb-${{ github.ref_name }}.apk"
          echo "New APK name will be: $NEW_NAME"
          
          # Get the directory of the original file
          APK_DIR=$(dirname "$ORIGINAL_PATH")
          
          # Create the new full path
          NEW_PATH="$APK_DIR/$NEW_NAME"
          
          # Rename the file
          mv "$ORIGINAL_PATH" "$NEW_PATH"
          
          # Output the new path for the release step
          echo "apk_path=$NEW_PATH" >> $GITHUB_OUTPUT

      # This step creates the release and intelligently marks it
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false # This ensures the release is not a draft
          # This is the magic part! It checks if the tag name contains '-alpha' or '-beta'.
          # If it does, the release is marked as a "Pre-release".
          # If it doesn't, it's marked as the "Latest release".
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') }}
          
          # This sets the title of the release page
          name: ${{ github.ref_name }}
          
          # This attaches your APK to the release
          files: ${{ steps.find_and_rename_apk.outputs.apk_path }} # Use the new step ID