name: Release Android APK

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags like v1.0.0
      - 'test-*' # Triggers on test tags like test-0.2.7

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive version from tag
        id: version
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Verify package version matches tag
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=${GITHUB_REF##*/}
          TAG_VERSION=${TAG_VERSION#v}
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "Package version $PKG_VERSION does not match tag v$TAG_VERSION" >&2
            exit 1
          fi

      - name: Build web assets
        run: npm run build

      - name: Capacitor sync (regenerate native + plugins)
        run: npx cap sync android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Prepare signing keystore (if provided)
        if: env.SIGNING_KEYSTORE_BASE64 != ''
        env:
          SIGNING_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 || '' }}
        run: |
          if [ -n "$SIGNING_KEYSTORE_BASE64" ]; then
            echo "$SIGNING_KEYSTORE_BASE64" | base64 -d > android/release.keystore
          fi

      - name: Build release & debug APKs
        working-directory: android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD || '' }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS || '' }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD || '' }}
        run: |
          if [ -f release.keystore ]; then
            echo 'Applying signing config via gradle properties'
            cat >> ../gradle.properties <<'EOF'
          MYAPP_UPLOAD_STORE_FILE=release.keystore
          MYAPP_UPLOAD_STORE_PASSWORD=$KEYSTORE_PASSWORD
          MYAPP_UPLOAD_KEY_ALIAS=$KEY_ALIAS
          MYAPP_UPLOAD_KEY_PASSWORD=$KEY_PASSWORD
          EOF
          fi
          ./gradlew assembleDebug assembleRelease --stacktrace

      - name: List generated APKs
        run: ls -R android/app/build/outputs/apk || true

      - name: Normalize APK filenames
        id: rename
        run: |
          VERSION=${{ steps.version.outputs.tag }}
          VERSION=${VERSION#v}
          OUTDIR=android/app/build/outputs/apk
          mkdir -p renamed
          # Debug APK
          for f in $(ls $OUTDIR/debug/*.apk 2>/dev/null || true); do
            cp "$f" "renamed/tgatb-${VERSION}-debug.apk"
          done
          # Release APK(s)
          for f in $(ls $OUTDIR/release/*.apk 2>/dev/null || true); do
            base=$(basename "$f")
            if echo "$base" | grep -qi 'unsigned'; then
              cp "$f" "renamed/tgatb-${VERSION}-unsigned.apk"
            else
              cp "$f" "renamed/tgatb-${VERSION}.apk"
            fi
          done
          ls -l renamed || true

      - name: Verify APK signature
        run: |
          VERSION=${{ steps.version.outputs.tag }}
          VERSION=${VERSION#v}
          jarsigner -verify -verbose -certs renamed/tgatb-${VERSION}.apk
        continue-on-error: false

      - name: Upload signed release APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: renamed/tgatb-${{ steps.version.outputs.tag }}.apk
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
